<?php

namespace Database\Seeders;

use App\Models\EduTool;
use Illuminate\Database\Seeder;

class EduToolSeeder extends Seeder
{
    public function run(): void
    {
        $tools = [
            // ══════════ DEVELOPMENT ══════════
            [
                'name' => 'GitHub Education',
                'slug' => 'github-education',
                'short_description' => 'GitHub Pro gratis + GitHub Copilot untuk pelajar',
                'description' => 'Dapatkan akses GitHub Pro secara gratis termasuk unlimited private repositories, GitHub Copilot AI assistant, GitHub Codespaces, dan 20+ developer tools lainnya melalui GitHub Student Developer Pack.',
                'icon_url' => 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png',
                'website_url' => 'https://education.github.com',
                'claim_url' => 'https://education.github.com/pack',
                'category' => 'development',
                'benefits' => [
                    'GitHub Pro (unlimited private repos)',
                    'GitHub Copilot gratis',
                    'GitHub Codespaces 90 jam/bulan',
                    'GitHub Actions 3000 menit/bulan',
                    '20+ partner offers (JetBrains, Azure, dll)',
                ],
                'how_to_claim' => "1. Buka education.github.com/pack\n2. Klik 'Get your Pack'\n3. Pilih 'Student'\n4. Verifikasi menggunakan email KVT (@kvt.x)\n5. Upload foto kartu pelajar jika diminta\n6. Tunggu persetujuan (1-7 hari)",
                'requirements' => ['Email KVT aktif', 'Kartu pelajar/surat keterangan', 'Usia 13+ tahun'],
                'requires_kvt_email' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'JetBrains Student',
                'slug' => 'jetbrains-student',
                'short_description' => 'Semua IDE JetBrains gratis (IntelliJ, PyCharm, WebStorm, dll)',
                'description' => 'Akses semua produk JetBrains secara gratis: IntelliJ IDEA Ultimate, PyCharm Professional, WebStorm, PhpStorm, CLion, DataGrip, dan lainnya. Lisensi berlaku 1 tahun dan bisa diperpanjang selama masih berstatus pelajar.',
                'icon_url' => 'https://resources.jetbrains.com/storage/products/company/brand/logos/jb_beam.png',
                'website_url' => 'https://www.jetbrains.com/community/education/',
                'claim_url' => 'https://www.jetbrains.com/shop/eform/students',
                'category' => 'development',
                'benefits' => [
                    'IntelliJ IDEA Ultimate',
                    'PyCharm Professional',
                    'WebStorm, PhpStorm, CLion',
                    'DataGrip, GoLand, Rider',
                    'ReSharper & dotMemory',
                ],
                'how_to_claim' => "1. Buka jetbrains.com/shop/eform/students\n2. Pilih 'Official document'\n3. Masukkan email KVT sebagai email institusi\n4. Verifikasi email\n5. Buat akun JetBrains\n6. Download IDE dari Toolbox App",
                'requirements' => ['Email KVT aktif', 'Status pelajar aktif'],
                'requires_kvt_email' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Visual Studio Dev Essentials',
                'slug' => 'vs-dev-essentials',
                'short_description' => 'Azure credits $100 + Visual Studio Enterprise + LinkedIn Learning',
                'description' => 'Microsoft menyediakan paket lengkap untuk pelajar termasuk $100 Azure credits, Visual Studio Enterprise, akses ke Microsoft Learn, dan berbagai tools development lainnya. Cocok untuk belajar cloud computing dan .NET development.',
                'icon_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Visual_Studio_Icon_2022.svg/1200px-Visual_Studio_Icon_2022.svg.png',
                'website_url' => 'https://azure.microsoft.com/en-us/free/students/',
                'claim_url' => 'https://azure.microsoft.com/en-us/free/students/',
                'category' => 'development',
                'benefits' => [
                    'Azure $100 free credits',
                    'Visual Studio Enterprise',
                    'Azure DevOps gratis',
                    'GitHub Enterprise via Student Pack',
                    'Microsoft Learn premium content',
                ],
                'how_to_claim' => "1. Buka aka.ms/azure4students\n2. Klik 'Start free'\n3. Login/buat akun Microsoft\n4. Verifikasi status pelajar dengan email KVT\n5. Dapatkan $100 Azure credits",
                'requirements' => ['Email KVT aktif', 'Usia 18+ untuk Azure'],
                'requires_kvt_email' => true,
                'sort_order' => 3,
            ],
            [
                'name' => 'Replit Education',
                'slug' => 'replit-education',
                'short_description' => 'Online IDE + AI code assistant gratis untuk pelajar',
                'description' => 'Replit menyediakan lingkungan coding online yang mendukung 50+ bahasa pemrograman. Dengan fitur Teams for Education, siswa dan guru bisa berkolaborasi secara real-time dalam proyek coding.',
                'icon_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/New_Replit_Logo.svg/1200px-New_Replit_Logo.svg.png',
                'website_url' => 'https://replit.com/site/teams-for-education',
                'claim_url' => 'https://replit.com/site/teams-for-education',
                'category' => 'development',
                'benefits' => [
                    'Online IDE 50+ bahasa',
                    'AI code assistant (Ghostwriter)',
                    'Real-time collaboration',
                    'Hosting project gratis',
                    'Teams for Education gratis',
                ],
                'how_to_claim' => "1. Buka replit.com/signup\n2. Daftar dengan email KVT\n3. Verifikasi email\n4. Apply untuk Teams for Education",
                'requirements' => ['Email KVT aktif'],
                'requires_kvt_email' => true,
                'sort_order' => 4,
            ],

            // ══════════ DESIGN ══════════
            [
                'name' => 'Figma Education',
                'slug' => 'figma-education',
                'short_description' => 'Figma Professional Plan gratis untuk pelajar & guru',
                'description' => 'Akses semua fitur Figma Professional secara gratis termasuk unlimited projects, unlimited version history, custom file/user permissions, shared & private projects, dan dev mode. Sempurna untuk belajar UI/UX design.',
                'icon_url' => 'https://upload.wikimedia.org/wikipedia/commons/3/33/Figma-logo.svg',
                'website_url' => 'https://www.figma.com/education/',
                'claim_url' => 'https://www.figma.com/education/apply',
                'category' => 'design',
                'benefits' => [
                    'Figma Professional Plan gratis',
                    'Unlimited projects & files',
                    'FigJam (online whiteboard)',
                    'Dev Mode untuk handoff',
                    'Shared & private projects',
                    'Unlimited version history',
                ],
                'how_to_claim' => "1. Buka figma.com/education/apply\n2. Masukkan email KVT\n3. Pilih role (siswa/guru)\n4. Isi informasi sekolah\n5. Submit dan tunggu verifikasi (1-3 hari)",
                'requirements' => ['Email KVT aktif', 'Bukti status pelajar/guru'],
                'requires_kvt_email' => true,
                'sort_order' => 5,
            ],
            [
                'name' => 'Canva Education',
                'slug' => 'canva-education',
                'short_description' => 'Canva Pro gratis + 100 juta asset premium untuk pendidikan',
                'description' => 'Canva for Education memberikan akses ke semua fitur premium Canva secara gratis: template premium, brand kit, background remover, content planner, dan kolaborasi tim tanpa batas. Cocok untuk membuat presentasi, poster, dan konten edukasi.',
                'icon_url' => 'https://upload.wikimedia.org/wikipedia/commons/0/08/Canva_icon_2021.svg',
                'website_url' => 'https://www.canva.com/education/',
                'claim_url' => 'https://www.canva.com/edu-signup/',
                'category' => 'design',
                'benefits' => [
                    'Canva Pro gratis sepenuhnya',
                    '100+ juta foto, video, audio premium',
                    'Background remover',
                    'Brand Kit & Magic Resize',
                    'Content planner & scheduling',
                    'Kolaborasi tim tanpa batas',
                ],
                'how_to_claim' => "1. Buka canva.com/edu-signup\n2. Masukkan email KVT\n3. Verifikasi status pendidik/pelajar\n4. Dapatkan akses penuh langsung",
                'requirements' => ['Email KVT aktif'],
                'requires_kvt_email' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'Adobe Creative Cloud',
                'slug' => 'adobe-creative-cloud',
                'short_description' => 'Diskon 60%+ untuk all apps: Photoshop, Illustrator, Premiere Pro',
                'description' => 'Adobe menawarkan diskon besar untuk pelajar dan guru. Akses 20+ creative apps termasuk Photoshop, Illustrator, Premiere Pro, After Effects, InDesign, XD, dan lainnya dengan harga spesial pelajar.',
                'icon_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Adobe_Creative_Cloud_rainbow_icon.svg/1200px-Adobe_Creative_Cloud_rainbow_icon.svg.png',
                'website_url' => 'https://www.adobe.com/creativecloud/plans.html',
                'claim_url' => 'https://www.adobe.com/creativecloud/buy/students.html',
                'category' => 'design',
                'benefits' => [
                    'Diskon 60%+ dari harga normal',
                    'Photoshop, Illustrator, InDesign',
                    'Premiere Pro, After Effects',
                    'Adobe XD, Lightroom',
                    '100GB cloud storage',
                    'Adobe Fonts & Portfolio',
                ],
                'how_to_claim' => "1. Buka adobe.com/creativecloud/buy/students\n2. Verifikasi status pelajar via SheerID\n3. Masukkan email KVT sebagai email sekolah\n4. Pilih paket dan bayar dengan harga pelajar",
                'requirements' => ['Email KVT aktif', 'Verifikasi SheerID', 'Usia 13+ tahun'],
                'requires_kvt_email' => true,
                'sort_order' => 7,
            ],

            // ══════════ PRODUCTIVITY ══════════
            [
                'name' => 'Notion Education',
                'slug' => 'notion-education',
                'short_description' => 'Notion Plus plan gratis + AI unlimited untuk pelajar',
                'description' => 'Notion memberikan akses Plus plan gratis untuk pelajar dan guru. Fitur termasuk unlimited blocks, unlimited file uploads, 30-day version history, dan Notion AI. Sempurna untuk manajemen proyek, catatan, dan kolaborasi.',
                'icon_url' => 'https://upload.wikimedia.org/wikipedia/commons/4/45/Notion_app_logo.png',
                'website_url' => 'https://www.notion.so/product/notion-for-education',
                'claim_url' => 'https://www.notion.so/product/notion-for-education',
                'category' => 'productivity',
                'benefits' => [
                    'Notion Plus plan gratis',
                    'Notion AI unlimited',
                    'Unlimited blocks & pages',
                    'Unlimited file uploads',
                    '30-day version history',
                    'Kolaborasi tim tanpa batas',
                ],
                'how_to_claim' => "1. Buat akun Notion dengan email KVT\n2. Buka Settings > Account\n3. Pilih 'Claim education plan'\n4. Verifikasi email KVT\n5. Plan otomatis upgrade ke Plus",
                'requirements' => ['Email KVT aktif'],
                'requires_kvt_email' => true,
                'sort_order' => 8,
            ],
            [
                'name' => 'Google Workspace for Education',
                'slug' => 'google-workspace-edu',
                'short_description' => 'Google Drive unlimited + Classroom + Meet premium untuk sekolah',
                'description' => 'Google Workspace for Education menyediakan suite lengkap tools kolaborasi: Gmail, Google Drive (pooled storage 100TB), Google Classroom, Google Meet premium, Google Docs, Sheets, Slides, dan lainnya untuk seluruh sekolah.',
                'icon_url' => 'https://lh3.googleusercontent.com/6MmhMjkjr0TGjQPT3SaXMyxOqkMf0RGNaYaFf8HRZF2XwTc9UPocQMTgkeVCf_Hv3M1DwApLsQ',
                'website_url' => 'https://edu.google.com/workspace-for-education/',
                'claim_url' => 'https://edu.google.com/get-started/',
                'category' => 'productivity',
                'benefits' => [
                    'Email @domain sekolah via Gmail',
                    'Google Drive 100TB pooled storage',
                    'Google Classroom',
                    'Google Meet (250 participants, recording)',
                    'Google Docs, Sheets, Slides, Forms',
                    'Admin console & security',
                ],
                'how_to_claim' => "1. Admin sekolah apply di edu.google.com\n2. Verifikasi domain sekolah\n3. Setup Google Admin Console\n4. Buat akun untuk guru & siswa\n5. Atau gunakan email KVT untuk verifikasi pelajar",
                'requirements' => ['Registrasi oleh admin sekolah', 'Domain sekolah terverifikasi'],
                'requires_kvt_email' => false,
                'sort_order' => 9,
            ],
            [
                'name' => 'Microsoft 365 Education',
                'slug' => 'microsoft-365-edu',
                'short_description' => 'Office 365 gratis: Word, Excel, PowerPoint, Teams + 1TB OneDrive',
                'description' => 'Dapatkan Microsoft 365 Education gratis termasuk Word, Excel, PowerPoint, OneNote, Microsoft Teams, dan 1TB OneDrive storage. Tersedia versi desktop dan web, sempurna untuk tugas sekolah dan presentasi.',
                'icon_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/1200px-Microsoft_logo.svg.png',
                'website_url' => 'https://www.microsoft.com/en-us/education/products/office',
                'claim_url' => 'https://www.microsoft.com/en-us/education/products/office',
                'category' => 'productivity',
                'benefits' => [
                    'Word, Excel, PowerPoint gratis',
                    'Microsoft Teams premium',
                    '1TB OneDrive storage',
                    'OneNote (Class Notebook)',
                    'Forms, Sway, Stream',
                    'Minecraft: Education Edition',
                ],
                'how_to_claim' => "1. Buka microsoft.com/education\n2. Masukkan email KVT\n3. Verifikasi status pelajar\n4. Download Office apps\n5. Login dengan akun Microsoft baru",
                'requirements' => ['Email KVT aktif'],
                'requires_kvt_email' => true,
                'sort_order' => 10,
            ],

            // ══════════ LEARNING ══════════
            [
                'name' => 'Coursera for Campus',
                'slug' => 'coursera-campus',
                'short_description' => 'Akses 5000+ kursus dari universitas top dunia gratis',
                'description' => 'Coursera for Campus memberikan akses ke ribuan kursus dari universitas dan perusahaan top dunia: Google, IBM, Stanford, Yale, dan lainnya. Termasuk guided projects, professional certificates, dan specializations.',
                'icon_url' => 'https://upload.wikimedia.org/wikipedia/commons/9/97/Coursera-Logo_600x600.svg',
                'website_url' => 'https://www.coursera.org/campus',
                'claim_url' => 'https://www.coursera.org/campus/register',
                'category' => 'learning',
                'benefits' => [
                    '5000+ kursus gratis',
                    'Sertifikat dari universitas top',
                    'Google, IBM, Meta certificates',
                    'Guided projects',
                    'Video lectures & quizzes',
                    'Peer-graded assignments',
                ],
                'how_to_claim' => "1. Admin sekolah daftar di coursera.org/campus\n2. Atau daftar individual dengan email KVT\n3. Verifikasi status pelajar\n4. Browse dan enroll kursus",
                'requirements' => ['Email KVT aktif', 'Registrasi institusi (opsional)'],
                'requires_kvt_email' => true,
                'sort_order' => 11,
            ],
            [
                'name' => 'LinkedIn Learning',
                'slug' => 'linkedin-learning',
                'short_description' => '16,000+ kursus video profesional untuk pengembangan skill',
                'description' => 'Akses library LinkedIn Learning dengan 16,000+ kursus dalam bidang bisnis, teknologi, dan kreativitas. Termasuk learning paths, exercise files, dan sertifikat yang bisa ditampilkan di profil LinkedIn.',
                'icon_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/LinkedIn_logo_initials.png/800px-LinkedIn_logo_initials.png',
                'website_url' => 'https://www.linkedin.com/learning/',
                'claim_url' => 'https://www.linkedin.com/learning/',
                'category' => 'learning',
                'benefits' => [
                    '16,000+ kursus video',
                    'Exercise files',
                    'Sertifikat LinkedIn',
                    'Learning paths terstruktur',
                    'Offline viewing',
                    'Personalized recommendations',
                ],
                'how_to_claim' => "1. Melalui GitHub Student Developer Pack\n2. Atau melalui Microsoft 365 Education\n3. Aktivasi dengan email KVT\n4. Akses 1 bulan gratis",
                'requirements' => ['GitHub Student Pack atau Microsoft 365 Education'],
                'requires_kvt_email' => false,
                'sort_order' => 12,
            ],

            // ══════════ CLOUD ══════════
            [
                'name' => 'AWS Educate',
                'slug' => 'aws-educate',
                'short_description' => 'Cloud computing credits + hands-on labs dari Amazon Web Services',
                'description' => 'AWS Educate memberikan akses ke cloud computing resources, hands-on labs, dan learning pathways. Pelajar mendapatkan AWS credits untuk bereksperimen dengan services seperti EC2, S3, Lambda, dan lainnya.',
                'icon_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Amazon_Web_Services_Logo.svg/1200px-Amazon_Web_Services_Logo.svg.png',
                'website_url' => 'https://aws.amazon.com/education/awseducate/',
                'claim_url' => 'https://aws.amazon.com/education/awseducate/',
                'category' => 'cloud',
                'benefits' => [
                    'AWS credits gratis',
                    'Hands-on labs',
                    'Cloud computing pathways',
                    'EC2, S3, Lambda, RDS access',
                    'AWS Certified Cloud Practitioner prep',
                    'Career pathways & job board',
                ],
                'how_to_claim' => "1. Buka awseducate.com\n2. Klik 'Join AWS Educate'\n3. Pilih 'Student'\n4. Masukkan email KVT\n5. Verifikasi dan mulai belajar",
                'requirements' => ['Email KVT aktif', 'Usia 14+ tahun'],
                'requires_kvt_email' => true,
                'sort_order' => 13,
            ],
            [
                'name' => 'Google Cloud for Students',
                'slug' => 'google-cloud-students',
                'short_description' => 'Google Cloud credits + Qwiklabs hands-on labs gratis',
                'description' => 'Google Cloud menyediakan credits dan hands-on labs melalui program Student Innovators. Akses ke Google Cloud Platform services, Qwiklabs/Cloud Skills Boost, dan kesempatan mendapatkan Google Cloud certifications.',
                'icon_url' => 'https://lh3.googleusercontent.com/VEnnK2SyklusfxZ3dIYjlQH3xSwK2BFSJ69TFQ0TjKAT3BFQM36GhTz3pKWmMXr5OcXN',
                'website_url' => 'https://cloud.google.com/edu',
                'claim_url' => 'https://cloud.google.com/edu/students',
                'category' => 'cloud',
                'benefits' => [
                    'Google Cloud credits',
                    'Qwiklabs / Cloud Skills Boost',
                    'Hands-on labs gratis',
                    'Google Cloud certification prep',
                    'Student Innovators program',
                    'GCP services access',
                ],
                'how_to_claim' => "1. Buka cloud.google.com/edu/students\n2. Daftar dengan email KVT\n3. Verifikasi status pelajar\n4. Akses labs dan credits",
                'requirements' => ['Email KVT aktif', 'GitHub Student Pack (opsional)'],
                'requires_kvt_email' => true,
                'sort_order' => 14,
            ],
            [
                'name' => 'DigitalOcean Student',
                'slug' => 'digitalocean-student',
                'short_description' => '$200 free credits untuk cloud server + managed databases',
                'description' => 'Melalui GitHub Student Developer Pack, DigitalOcean memberikan $200 credits yang bisa digunakan untuk Droplets (VPS), Managed Databases, Kubernetes, Spaces (Object Storage), dan App Platform.',
                'icon_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/DigitalOcean_logo.svg/1200px-DigitalOcean_logo.svg.png',
                'website_url' => 'https://www.digitalocean.com',
                'claim_url' => 'https://education.github.com/pack',
                'category' => 'cloud',
                'benefits' => [
                    '$200 free credits (via GitHub Student Pack)',
                    'Droplets (VPS) dari $4/bulan',
                    'Managed Databases',
                    'Kubernetes clusters',
                    'Spaces Object Storage',
                    'App Platform untuk deploy',
                ],
                'how_to_claim' => "1. Dapatkan GitHub Student Developer Pack dulu\n2. Buka education.github.com/pack\n3. Cari DigitalOcean di partner list\n4. Klik 'Get access'\n5. Buat akun DigitalOcean\n6. Credits otomatis ditambahkan",
                'requirements' => ['GitHub Student Developer Pack aktif'],
                'requires_kvt_email' => false,
                'sort_order' => 15,
            ],

            // ══════════ AI ══════════
            [
                'name' => 'GitHub Copilot',
                'slug' => 'github-copilot',
                'short_description' => 'AI pair programmer powered by OpenAI — gratis untuk pelajar',
                'description' => 'GitHub Copilot adalah AI coding assistant yang terintegrasi langsung ke VS Code, JetBrains IDE, dan Neovim. Bisa auto-complete code, generate functions, menulis tests, dan menjelaskan code. Gratis sepenuhnya via GitHub Student Developer Pack.',
                'icon_url' => 'https://github.githubassets.com/images/modules/site/copilot/copilot.png',
                'website_url' => 'https://github.com/features/copilot',
                'claim_url' => 'https://education.github.com/pack',
                'category' => 'ai',
                'benefits' => [
                    'AI code completion di IDE',
                    'Code generation dari komentar',
                    'Multi-language support (Python, JS, PHP, dll)',
                    'Chat mode untuk tanya jawab code',
                    'Code explanation & refactoring',
                    'Test generation otomatis',
                ],
                'how_to_claim' => "1. Dapatkan GitHub Student Developer Pack\n2. Buka github.com/settings/copilot\n3. Copilot otomatis aktif (gratis)\n4. Install extension di VS Code\n5. Login dan mulai coding",
                'requirements' => ['GitHub Student Developer Pack aktif'],
                'requires_kvt_email' => false,
                'sort_order' => 16,
            ],
            [
                'name' => 'OpenAI API Credits',
                'slug' => 'openai-api-credits',
                'short_description' => 'API credits untuk GPT-4, DALL-E, Whisper — build AI apps',
                'description' => 'OpenAI menyediakan API credits untuk pelajar melalui berbagai program partnership. Gunakan untuk mengakses GPT-4, GPT-3.5, DALL-E image generation, Whisper speech-to-text, dan Embeddings untuk proyek AI/ML.',
                'icon_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/OpenAI_Logo.svg/1200px-OpenAI_Logo.svg.png',
                'website_url' => 'https://platform.openai.com',
                'claim_url' => 'https://platform.openai.com/signup',
                'category' => 'ai',
                'benefits' => [
                    'Free tier API credits',
                    'GPT-4 & GPT-3.5 Turbo access',
                    'DALL-E image generation',
                    'Whisper speech-to-text',
                    'Embeddings untuk search/recommend',
                    'Fine-tuning capabilities',
                ],
                'how_to_claim' => "1. Buat akun di platform.openai.com\n2. Verifikasi email dan nomor HP\n3. Dapatkan free trial credits\n4. Gunakan untuk proyek sekolah\n5. Apply ke edu programs untuk credits tambahan",
                'requirements' => ['Email aktif', 'Nomor HP untuk verifikasi'],
                'requires_kvt_email' => false,
                'sort_order' => 17,
            ],

            // ══════════ COMMUNICATION ══════════
            [
                'name' => 'Zoom Education',
                'slug' => 'zoom-education',
                'short_description' => 'Zoom Pro gratis untuk sekolah — unlimited meetings & recording',
                'description' => 'Zoom for Education menyediakan lisensi Pro/Business gratis untuk institusi pendidikan. Fitur termasuk unlimited meeting duration, cloud recording, breakout rooms, polling, dan virtual backgrounds.',
                'icon_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Zoom_Communications_Logo.svg/1200px-Zoom_Communications_Logo.svg.png',
                'website_url' => 'https://zoom.us/education',
                'claim_url' => 'https://zoom.us/education',
                'category' => 'communication',
                'benefits' => [
                    'Meeting tanpa batas waktu',
                    'Cloud recording',
                    'Breakout rooms',
                    'Polling & reactions',
                    '300 participants',
                    'Virtual backgrounds & filters',
                ],
                'how_to_claim' => "1. Admin sekolah apply di zoom.us/education\n2. Verifikasi institusi pendidikan\n3. Dapatkan lisensi untuk guru & siswa\n4. Atau join dengan email KVT",
                'requirements' => ['Registrasi oleh admin sekolah', 'Email KVT (opsional)'],
                'requires_kvt_email' => false,
                'sort_order' => 18,
            ],
            [
                'name' => 'Discord Student Hub',
                'slug' => 'discord-student-hub',
                'short_description' => 'Komunitas pelajar + Nitro benefits + server sekolah terverifikasi',
                'description' => 'Discord Student Hubs menghubungkan pelajar dari sekolah yang sama dalam satu hub terverifikasi. Fitur termasuk exclusive student channels, server discovery, dan akses ke komunitas pelajar lainnya.',
                'icon_url' => 'https://assets-global.website-files.com/6257adef93867e50d84d30e2/636e0a6ca814282eca7172c6_icon_clyde_white_RGB.svg',
                'website_url' => 'https://discord.com/student-hubs',
                'claim_url' => 'https://discord.com/student-hubs',
                'category' => 'communication',
                'benefits' => [
                    'Student Hub terverifikasi',
                    'Server sekolah exclusive',
                    'Student-only channels',
                    'Study groups & voice channels',
                    'Bot integration',
                    'Community discovery',
                ],
                'how_to_claim' => "1. Buka Discord > Student Hubs\n2. Verifikasi email KVT\n3. Join hub sekolah\n4. Atau buat hub baru untuk sekolah",
                'requirements' => ['Email KVT aktif', 'Akun Discord'],
                'requires_kvt_email' => true,
                'sort_order' => 19,
            ],
            [
                'name' => '1Password Student',
                'slug' => '1password-student',
                'short_description' => 'Password manager premium gratis via GitHub Student Pack',
                'description' => '1Password menyediakan langganan gratis selama 1 tahun melalui GitHub Student Developer Pack. Simpan dan kelola semua password, credit cards, secure notes, dan dokumen sensitif lainnya dengan enkripsi end-to-end.',
                'icon_url' => 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/1Password_logo_2022.svg/1200px-1Password_logo_2022.svg.png',
                'website_url' => 'https://1password.com/students',
                'claim_url' => 'https://education.github.com/pack',
                'category' => 'productivity',
                'benefits' => [
                    '1 tahun gratis 1Password',
                    'Unlimited passwords & items',
                    'Cross-platform (Mac, Windows, iOS, Android)',
                    'Browser extensions',
                    'Watchtower security alerts',
                    'Travel Mode',
                ],
                'how_to_claim' => "1. Dapatkan GitHub Student Developer Pack\n2. Buka partner offers di Pack\n3. Klik 1Password dan 'Get access'\n4. Buat akun 1Password\n5. Langganan otomatis aktif 1 tahun",
                'requirements' => ['GitHub Student Developer Pack aktif'],
                'requires_kvt_email' => false,
                'sort_order' => 20,
            ],
        ];

        foreach ($tools as $tool) {
            EduTool::create($tool);
        }

        $this->command->info('   ✅ EduToolSeeder: ' . count($tools) . ' tools edukasi');
    }
}
